# Generated by Django 3.0.7 on 2021-06-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_alter_user_status_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_status',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
