# Generated by Django 3.0.7 on 2021-06-23 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210621_2318'),
        ('authentication', '0003_auto_20210621_1633'),
    ]

    operations = [
    ]
