# Generated by Django 3.0.7 on 2021-06-24 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_auto_20210620_0215'),
        ('authentication', '0004_merge_20210623_2156'),
    ]

    operations = [
    ]
