# Generated by Django 3.0.7 on 2021-06-24 10:55

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0005_merge_20210624_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='Seeker_Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('condition', models.TextField()),
                ('location', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('user_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authentication.User_status')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
