# Generated by Django 3.0.7 on 2021-06-24 12:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woodogdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seeker_post',
            name='location',
            field=models.CharField(max_length=200),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_connect', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='woodogdata.Seeker_Post')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
