# Generated by Django 3.0.7 on 2021-07-12 11:05

from django.db import migrations, models
import froala_editor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0002_auto_20210624_1738'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=1000)),
                ('content', froala_editor.fields.FroalaField()),
                ('tag', models.CharField(max_length=100)),
                ('author_name', models.CharField(max_length=50)),
                ('slug', models.SlugField(max_length=1000)),
                ('image', models.ImageField(upload_to='Media')),
                ('date_Time', models.DateTimeField(auto_now_add=True)),
                ('upload_to', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
