# Generated by Django 3.0.7 on 2021-07-11 15:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0003_gallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gallery',
            options={'ordering': ['-uploading_date']},
        ),
        migrations.AddField(
            model_name='gallery',
            name='title',
            field=models.CharField(default=3, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gallery',
            name='uploading_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='tag',
            field=models.CharField(max_length=100),
        ),
    ]
