# Generated by Django 3.0.7 on 2021-07-12 14:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('woodogdata', '0004_auto_20210712_1902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogmodel',
            old_name='date_Time',
            new_name='created_date_time',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='author_name',
        ),
        migrations.RemoveField(
            model_name='blogmodel',
            name='upload_to',
        ),
        migrations.AddField(
            model_name='blogmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
