# Generated by Django 3.0.7 on 2021-07-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0004_auto_20210711_2106'),
        ('woodogdata', '0005_auto_20210712_1941'),
    ]

    operations = [
    ]
