# Generated by Django 3.0.7 on 2021-07-19 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0006_merge_20210718_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tag',
            field=models.IntegerField(),
        ),
    ]
