# Generated by Django 3.0.7 on 2021-07-19 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0007_auto_20210719_1120'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={},
        ),
    ]
