# Generated by Django 3.0.7 on 2021-07-19 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0008_auto_20210719_1547'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogmodel',
            options={'ordering': ['-created_date_time']},
        ),
        migrations.AlterField(
            model_name='blogmodel',
            name='content',
            field=models.TextField(),
        ),
    ]
