# Generated by Django 3.0.7 on 2021-07-23 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('woodogdata', '0008_auto_20210719_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogmodel',
            name='tag',
            field=models.CharField(choices=[('trending', 'trending'), ('latest', 'latest'), ('editor1', 'editor1'), ('editor2', 'editor2'), ('popular', 'popular')], default='latest', max_length=100),
        ),
    ]
